#!/usr/sbin/fish

# Cleanup old binaries
rm boot.bin
rm linkerout.bin

cargo build --release
echo "========== Unlinked Elf Information =========="
stat target/i386-unknown-none/release/jos
echo "========== Linked Elf Information =========="
llvm-objcopy -O binary target/i386-unknown-none/release/jos boot.bin
cp boot.bin linkerout.bin
stat linkerout.bin
truncate -s 510 boot.bin
printf "\x55\xAA" >> boot.bin
echo "========== Completed Build and Drive =========="
qemu-system-i386 -drive format=raw,file=boot.bin
